/**
 * Shared migration folder + slug helpers (create + diff --write).
 */

import { mkdir, writeFile, access } from 'fs/promises';
import { join } from 'path';
import { constants } from 'fs';
import { resolveDdpConfig, resolveDdpMigrationsDir } from '@/utils/ddpConfig';
import { ensureDirectory } from '@/utils/filesystem';
import { logInfo } from '@/utils/logger';

const MIGRATION_DIR_PATTERN = /^\d{14}_[a-z0-9_]+$/;

export const sanitizeMigrationSlug = (raw: string): string => {
  const lower = raw.trim().toLowerCase();
  const replaced = lower.replace(/[^a-z0-9_]+/g, '_');
  const collapsed = replaced.replace(/_+/g, '_');
  const trimmed = collapsed.replace(/^_+|_+$/g, '');
  if (!trimmed) {
    throw new Error('Migration name is empty after sanitization');
  }
  if (trimmed.length > 120) {
    throw new Error('Migration name is too long (max 120 characters)');
  }
  return trimmed;
};

export const utcTimestamp14 = (): string => {
  const d = new Date();
  const p = (n: number, w: number) => n.toString().padStart(w, '0');
  return (
    `${d.getUTCFullYear()}` +
    `${p(d.getUTCMonth() + 1, 2)}` +
    `${p(d.getUTCDate(), 2)}` +
    `${p(d.getUTCHours(), 2)}` +
    `${p(d.getUTCMinutes(), 2)}` +
    `${p(d.getUTCSeconds(), 2)}`
  );
};

export const migrationDirExists = async (path: string): Promise<boolean> => {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
};

export const migrationIdPattern = MIGRATION_DIR_PATTERN;

export interface IMigrationWriteFromDiffInput {
  name: string;
  upSql: string;
  backfillSql?: string;
  constraintsSql?: string;
  verifySql?: string;
}

/** Create a timestamped migration folder and write `up.sql` (e.g. from `migration diff`). */
export const migrationWriteFromDiff = async (
  options: IMigrationWriteFromDiffInput
): Promise<{ migrationId: string; targetDir: string }> => {
  const slug = sanitizeMigrationSlug(options.name);
  const resolved = await resolveDdpConfig();
  if (!resolved) {
    throw new Error('ddp.config.json not found.');
  }

  const migrationsDir = await resolveDdpMigrationsDir();
  await ensureDirectory(migrationsDir);

  const migrationId = `${utcTimestamp14()}_${slug}`;
  if (!MIGRATION_DIR_PATTERN.test(migrationId)) {
    throw new Error(`Invalid migration id "${migrationId}"`);
  }

  const targetDir = join(migrationsDir, migrationId);
  if (await migrationDirExists(targetDir)) {
    throw new Error(
      `Migration directory already exists: ${targetDir}\nChoose a different --migration-name.`
    );
  }

  await mkdir(targetDir, { recursive: true });

  const header =
    `-- DDP migration: ${migrationId}\n` +
    `-- Generated by: ddp migration diff (state → shadow vs target)\n\n`;

  await writeFile(
    join(targetDir, 'up.sql'),
    `${header}${options.upSql.trim()}\n`,
    'utf8'
  );

  if (options.backfillSql && options.backfillSql.trim().length > 0) {
    const backfillHeader =
      `-- DDP migration backfill: ${migrationId}\n` +
      '-- Generated by: ddp migration diff (safe backfill scaffold)\n\n';
    await writeFile(
      join(targetDir, 'backfill.sql'),
      `${backfillHeader}${options.backfillSql.trim()}\n`,
      'utf8'
    );

    await writeFile(
      join(targetDir, 'expand.sql'),
      `${header}${options.upSql.trim()}\n`,
      'utf8'
    );

    if (options.verifySql && options.verifySql.trim().length > 0) {
      await writeFile(
        join(targetDir, 'backfill.verify.sql'),
        `${options.verifySql.trim()}\n`,
        'utf8'
      );
    }

    if (options.constraintsSql && options.constraintsSql.trim().length > 0) {
      const contractHeader =
        `-- DDP migration contract: ${migrationId}\n` +
        '-- Generated by: ddp migration diff (final constraints)\n\n';
      await writeFile(
        join(targetDir, 'constraints.sql'),
        `${contractHeader}${options.constraintsSql.trim()}\n`,
        'utf8'
      );
    }
  }

  logInfo('Wrote migration from diff', { migrationId, targetDir });

  return { migrationId, targetDir };
};
